fin/fin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('finance/', include('finance.urls', namespace='finance')),
]

fin/finance/urls.py
from django.urls import path
from .views import category_views, home_views, transaction_views, report_views
from django.contrib.auth import views as auth_views


app_name = 'finance'


urlpatterns = [

    path('', home_views.home, name='home'),

    # categories
    # path('categories/', category_views.category_list, name='category_list'),
    path('categories/', category_views.CategoryList.as_view(), name='category_list'),
    path('categories/create/', category_views.category_create, name='category_create'),
    path('categories/<int:pk>/delete/', category_views.category_delete, name='category_delete'),
    path('categories/<int:pk>/update/', category_views.category_update, name='category_update'),

    # transactions
    path('transaction/', transaction_views.TransactionList.as_view(), name='transaction_list'),
    path('transaction/create/', transaction_views.transaction_create, name='transaction_create'),
    path('transaction/<int:pk>/delete/', transaction_views.transaction_delete, name='transaction_delete'),
    path('transaction/<int:pk>/update/', transaction_views.transaction_update, name='transaction_update'),

    # reports
    path('report/', report_views.report, name='report'),

    # account
    path('login/', auth_views.LoginView.as_view(template_name='finance/account/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='finance/account/logout.html'), name='logout'),
    path('register/', home_views.register, name='register'),
]

fin/finance/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, default=None, null=True)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class Transaction(models.Model):
    CHOICES = (
        ('spending', 'Spending'),
        ('revenue', 'Revenue'),
    )
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    type_operation = models.CharField(max_length=200, choices=CHOICES, default='spending')
    total = models.DecimalField(max_digits=6, decimal_places=2)
    date = models.DateField()
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, default=None, null=True)

fin/finance/forms.py
from django import forms
from .models import Transaction, Category
from bootstrap_datepicker_plus import DatePickerInput
from django.contrib.auth.models import User


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ('category', 'type_operation', 'total', 'date', 'description')
        widgets = {
            'date': DatePickerInput(),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(TransactionForm, self).__init__(*args, **kwargs)
        self.fields['category'].queryset = Category.objects.filter(user=user)


class ReportForm(forms.Form):
    start_date = forms.DateField(widget=DatePickerInput())
    end_date = forms.DateField(widget=DatePickerInput())
    type_operation = forms.ChoiceField(choices=Transaction.CHOICES)

    def clean_end_date(self):
        end_date = self.cleaned_data['end_date']
        start_date = self.cleaned_data['start_date']
        if end_date < start_date:
            raise forms.ValidationError("End date must be greater when end date!")

        return end_date


class UserRegistrationForm(forms.ModelForm):
    password1 = forms.CharField(label='password',
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label='repeat password',
                                widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username',)

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

fin/finance/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Category
from django.views.generic import ListView
from django.http import Http404
from django.contrib import messages


CATEGORIES_SHOW = 10


class CategoryList(ListView):
    template_name = 'finance/category/list.html'
    context_object_name = 'categories'
    queryset = Category.objects.order_by('-created')[:CATEGORIES_SHOW]


# def category_list(request):
#     categories = Category.objects.all()
#     context = {'categories': categories,
#                'message': None}
#     return render(request, 'finance/category/list.html', context)


def category_create(request):
    if request.method == 'POST':
        try:
            name = request.POST.get('name')
            description = request.POST.get('description')
        except KeyError:
            raise Http404
        category = Category(name=name, description=description)
        category.save()
        messages.success(request, 'Category "{}" was successfully created'
                         .format(category.name))
        return redirect("finance:category_list")
    return render(request, 'finance/category/create_update.html')


def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    category.delete()
    messages.success(request, 'Category "{}" was successfully deleted'
                     .format(category.name))
    return redirect("finance:category_list")


def category_update(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == 'POST':
        name = request.POST.get('name', "")
        description = request.POST.get('description', "")
        old_name = category.name
        category.name = name
        category.description = description
        category.save()
        messages.success(request, 'Category "{}" was successfully updated on {}'
                         .format(old_name, category.name))
        return redirect("finance:category_list")
    update = True
    return render(request, "finance/category/create_update.html", {
        'category': category,
        'update': update,
    })

fin/finance/views/category_views.py
from django.shortcuts import render, redirect, get_object_or_404
from ..models import Category
from django.views.generic import ListView
from django.http import Http404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

CATEGORIES_SHOW = 10


class CategoryList(ListView):
    template_name = 'finance/category/list.html'
    context_object_name = 'categories'

    def get_queryset(self):
        return Category.objects.filter(user=self.request.user) \
                               .order_by('-created')[:CATEGORIES_SHOW]

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(CategoryList, self).dispatch(request, *args, **kwargs)


# def category_list(request):
#     categories = Category.objects.all()
#     context = {'categories': categories,
#                'message': None}
#     return render(request, 'finance/category/list.html', context)

@login_required
def category_create(request):
    if request.method == 'POST':
        try:
            name = request.POST.get('name')
            description = request.POST.get('description')
        except KeyError:
            raise Http404
        category = Category(user=request.user, name=name, description=description)
        category.save()
        messages.success(request, 'Category "{}" was successfully created'
                         .format(category.name))
        return redirect("finance:category_list")
    return render(request, 'finance/category/create_update.html')


@login_required
def category_delete(request, pk):
    category = get_object_or_404(Category, user=request.user, pk=pk)
    category.delete()
    messages.success(request, 'Category "{}" was successfully deleted'
                     .format(category.name))
    return redirect("finance:category_list")


@login_required
def category_update(request, pk):
    category = get_object_or_404(Category, user=request.user, pk=pk)
    if request.method == 'POST':
        name = request.POST.get('name', "")
        description = request.POST.get('description', "")
        old_name = category.name
        category.name = name
        category.description = description
        category.save()
        messages.success(request, 'Category "{}" was successfully updated on {}'
                         .format(old_name, category.name))
        return redirect("finance:category_list")
    update = True
    return render(request, "finance/category/create_update.html", {
        'category': category,
        'update': update,
    })

fin/finance/views/home_views.py
from django.shortcuts import render, redirect
from ..forms import UserRegistrationForm


def home(request):
    return render(request, 'finance/home.html')


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form
                                  .cleaned_data['password1'])
            new_user.save()
            return redirect('finance:home')
    else:
        form = UserRegistrationForm()
    return render(request, 'finance/account/register.html', {'form': form})

fin/finance/views/report_views.py
from django.shortcuts import render
from ..forms import ReportForm
from ..models import Transaction, Category
from django.db.models import Sum
from django.contrib.auth.decorators import login_required


import json
import datetime


@login_required
def report(request):
    if request.method == 'POST':
        form = ReportForm(request.POST)
        if form.is_valid():
            if 'pie' in request.POST:
                return render(request,
                              'finance/report/report_pie.html',
                              generate_pie_data(form, request))
            elif 'line' in request.POST:
                return render(request,
                              'finance/report/report_line.html',
                              generate_line_data(form, request))
    else:
        form = ReportForm()
    return render(request, 'finance/report/report.html', {'form': form})


def generate_pie_data(form, request):
    form_fields = form.cleaned_data
    transactions = Transaction.objects.filter(user=request.user,
                                              date__range=(form_fields['start_date'], form_fields['end_date']))\
                                      .filter(type_operation=form_fields['type_operation'])
    categories = Category.objects.filter(user=request.user).all()
    data_for_line = []
    for category in categories:
        total_sum = 0
        for transaction in transactions.filter(category=category):
            total_sum += float(transaction.total)
        data_for_line.append({'name': category.name, 'y': total_sum})

    context = dict()
    context['data'] = json.dumps(data_for_line)
    context['data_category_sum'] = data_for_line
    context['start_date'] = form_fields['start_date']
    context['end_date'] = form_fields['end_date']
    context['total_sum'] = sum(d['y'] for d in data_for_line)
    return context


def generate_line_data(form, request):
    form_fields = form.cleaned_data
    transactions = Transaction.objects.filter(user=request.user,
                                              date__range=(form_fields['start_date'], form_fields['end_date'])) \
                                      .filter(type_operation=form_fields['type_operation'])
    data_for_line = []
    sum_by_dates = transactions.values('date').annotate(data_sum=Sum('total'))
    dict_sum_by_dates = {v['date']: float(v['data_sum']) for v in sum_by_dates}
    date1 = form_fields['start_date']
    date2 = form_fields['end_date']
    day = datetime.timedelta(days=1)
    while date1 <= date2:
        if date1 not in dict_sum_by_dates.keys():
            data_for_line.append(0)
        else:
            data_for_line.append(dict_sum_by_dates[date1])
        date1 = date1 + day

    data = {'name': 'money', 'data': data_for_line}
    context = dict()
    context['data'] = json.dumps(data)
    context['start_date'] = form_fields['start_date']
    context['end_date'] = form_fields['end_date']
    context['start_date_format'] = form_fields['start_date'].strftime('%Y, %m, %d')
    return context

fin/finance/views/transaction_views.py
from django.shortcuts import render, redirect, get_object_or_404
from ..models import Transaction, Category
from django.views.generic import ListView
from django.contrib import messages
from ..forms import TransactionForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


TRANSACTION_SHOW = 10


class TransactionList(ListView):
    template_name = 'finance/transaction/list.html'
    context_object_name = 'transactions'

    def get_queryset(self):
        return Transaction.objects.filter(user=self.request.user)[:TRANSACTION_SHOW]

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(TransactionList, self).dispatch(request, *args, **kwargs)


@login_required
def transaction_create(request):
    if request.method == 'POST':
        form = TransactionForm(request.POST, user=request.user)
        if form.is_valid():
            transaction = form.save(commit=False)
            transaction.user = request.user
            transaction.save()
            messages.success(request, 'Transaction "{}" was successfully created'
                                      .format(transaction.description))
            return redirect("finance:transaction_list")
    else:
        form = TransactionForm(user=request.user)
    return render(request, 'finance/transaction/create_update.html', {'form': form,
                                                                      'choices': Transaction.CHOICES})


@login_required
def transaction_delete(request, pk):
    transaction = get_object_or_404(Transaction, user=request.user, pk=pk)
    transaction.delete()
    messages.success(request, 'Transaction "{}" was successfully deleted'
                     .format(transaction.description))
    return redirect("finance:transaction_list")


@login_required
def transaction_update(request, pk):
    transaction = get_object_or_404(Transaction, user=request.user, pk=pk)
    if request.method == 'POST':
        form = TransactionForm(request.POST, user=request.user, instance=transaction)
        if form.is_valid():
            current_transaction = form.save(commit=False)
            current_transaction.save()
            messages.success(request, 'Transaction "{}" was successfully updated on {}'
                             .format(transaction.description, current_transaction.description))
            return redirect("finance:transaction_list")
    else:
        data = {'category': transaction.category,
                'type_operation': transaction.type_operation,
                'total': transaction.total,
                'date': transaction.date,
                'description': transaction.description}
        form = TransactionForm(user=request.user, initial=data)
    update = True
    return render(request, "finance/transaction/create_update.html", {
        'update': update,
        'form': form,
    })

fin/finance/templates/finance/transaction/create_update.html
{% extends 'finance/base.html' %}


{% block title %}Create category{% endblock %}

{% block navbar %}
    {% include "finance/navbar.html" with active_nav='Transactions' %}
{% endblock %}

{% block content %}


{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{{ form.media }}
<div class="row">
    <div class="col-8">
<form action="." method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <!--<div class="form-group row">-->
        <!--<label for="category" class="col-sm-2 col-form-label">Category</label>-->
        <!--<div class="col-sm-6">-->
            <!--<select class="custom-select" id="category" name="category">-->
                <!--{% for category in categories %}-->
                    <!--<option value="{{ category.id }}">{{ category.name }}</option>-->
                <!--{% endfor %}-->
            <!--</select>-->
        <!--</div>-->
    <!--</div>-->

    <!--<div class="form-group row">-->
        <!--<label for="type_operation" class="col-sm-2 col-form-label">Type operation</label>-->
        <!--<div class="col-sm-6">-->
            <!--<select class="custom-select" id="type_operation" name="category">-->
                <!--{% for choice in choices %}-->
                    <!--<option>{{ choice.1 }}</option>-->
                <!--{% endfor %}-->
            <!--</select>-->
        <!--</div>-->
    <!--</div>-->

    <!--<div class="form-group row">-->
        <!--<label for="total" class="col-sm-2 col-form-label">Total amount</label>-->
        <!--<div class="col-sm-6">-->
            <!--<input type="text" class="form-control" id="total" value="{{ transaction.total }}" name="total">-->
        <!--</div>-->
    <!--</div>-->

    <!--<div class="form-group row">-->
        <!--<label for="description" class="col-sm-2 col-form-label">Description</label>-->
        <!--<div class="col-sm-6">-->
            <!--<input type="text" class="form-control" id="description" value="{{ transaction.description }}" name="description">-->
        <!--</div>-->
    <!--</div>-->

    <!--<div class="form-group row">-->
        <!--<label for="date" class="col-sm-2 col-form-label">Date</label>-->
            <!--<div class="col-sm-6">-->
                <!--<input type="date" class="form-control" id="date" value="{{ transaction.date }}" name="date">-->
            <!--</div>-->
    <!--</div>-->

    <div class="form-group row">
        <div class="col-sm-6">
            <button type="submit" class="btn btn-primary">{% if update %}Update{% else %}Create{% endif %}</button>
        </div>
        <div class="col-sm-1">
            <button type="reset" class="btn btn-primary">Reset</button>
        </div>
    </div>



</form>
        </div>
</div>
{% endblock %}

fin/finance/templates/finance/transaction/list.html
{% extends 'finance/base.html' %}

{% block title %}List of categories{% endblock %}

{% block navbar %}
    {% include "finance/navbar.html" with active_nav='Transactions' %}
{% endblock %}

{% block content %}

        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
              <div class="alert alert-primary" role="alert">

                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
              </div>
            {% endfor %}
        </ul>
        {% endif %}

        <table class="table">
          <thead class="thead-light">
            <tr>
              <th scope="col">#</th>
              <th scope="col">Category</th>
              <th scope="col">Type operation</th>
              <th scope="col">Total</th>
              <th scope="col">Date</th>
              <th scope="col">Description</th>
              <th scope="col">Control</th>
            </tr>
          </thead>
          <tbody>
          {% for transaction in transactions %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <td>{{ transaction.category }}</td>
              <td>{{ transaction.type_operation }}</td>
              <td>{{ transaction.total }}</td>
              <td>{{ transaction.date }}</td>
              <td>{{ transaction.description }}</td>
              <td>
                <a class="btn btn-primary" href="{% url 'finance:transaction_update' transaction.pk %}" role="button"><span class="fas fa-pen"></span> </a>
                <a class="btn btn-primary" href="{% url 'finance:transaction_delete' transaction.pk %}" role="button"><span class="fas fa-trash-alt"></span></a>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>

        <div>
          <a class="btn btn-primary float-left" href="{% url 'finance:transaction_create' %}" role="button">Create category</a>
        </div>
{% endblock %}